Support for custom Help page
finos/spring-bot pull request #304
Opened 2022-03-07 07:26 UTC by pankajpkhandelwal-db

Items addressed -

- Support for custom Help page
- Suppress button display in Help menu when command expects parameters
- Order Help menu items using `helpOrder` attribute in `@ChatRequest`
- Limit to either Symphony or Teams
- E.g. implementation in Demo Bot
- Resolves #283

2022-03-07 09:06 UTC, robmoffat requested changes
Pretty good - couple of suggestions from me

2022-03-07 09:06 UTC, robmoffat commented on demos/demo-bot/src/main/java/org/finos/springbot/example/demo/controller/CustomHelpController.java
> +    private static final String DEFAULT_FORMATTER_PATTERN = "(?<!(^|[A-Z]))(?=[A-Z])|(?<!^)(?=[A-Z][a-z])";
Couldn't this just be done in the FTL template?

2022-03-07 09:06 UTC, robmoffat commented on libs/chat-workflow/src/main/java/org/finos/springbot/workflow/help/HelpController.java
> +		if(addButton) {
This logic should be inside the "includeInHelp" function, otherwise you'll get CommandDescriptions added to the list that shouldn't be there.

2022-03-09 09:00 UTC, pankaj-a-khandelwal-db commented on demos/demo-bot/src/main/java/org/finos/springbot/example/demo/controller/CustomHelpController.java
> +    private static final String DEFAULT_FORMATTER_PATTERN = "(?<!(^|[A-Z]))(?=[A-Z])|(?<!^)(?=[A-Z][a-z])";
Yes, something similar can be added to FTL. 
However, have added it here just as an example showing that you can manipulate `Commands` for generating custom help.

2022-03-09 09:03 UTC, pankaj-a-khandelwal-db commented on libs/chat-workflow/src/main/java/org/finos/springbot/workflow/help/HelpController.java
> +		if(addButton) {
This does not adds `CommandDescriptions` - it just turns display of button On/Off on final list of Help menu items. 
Anyhow, this method call receives filtered list of `CommandDescriptions` from `includeInHelp`.

2022-03-09 09:27 UTC, robmoffat approved these changes

2022-03-09 12:29 UTC, merged