Compatible to Spring-boot 3x
finos/spring-bot pull request #406
Opened 2023-07-11 05:50 UTC by vaibhav-db

2023-07-11 08:57 UTC, robmoffat requested changes
coming together!

2023-07-11 08:57 UTC, robmoffat commented on libs/chat-workflow/src/main/java/org/finos/springbot/workflow/response/templating/AbstractResourceTemplateProvider.java
> -			LOG.debug("Couldn't find template: "+name);
I'm not sure it's always an error - remember spring bot will generate a template for you if one doesn't exist

2023-07-11 08:57 UTC, robmoffat commented on libs/teams/teams-chat-workflow-spring-boot-starter/src/main/java/org/finos/springbot/teams/bot/BotController.java
> +/**
Can you attach some javadoc to say where these classes come from and why we've added them rather than used the dependency?

thanks

2023-07-11 08:57 UTC, robmoffat commented on libs/teams/teams-chat-workflow-spring-boot-starter/src/main/java/org/finos/springbot/teams/bot/BotDependencyConfiguration.java
> +* SpringBootApplication annotation).
same for this one

2023-07-11 08:57 UTC, robmoffat commented on libs/teams/teams-chat-workflow-spring-boot-starter/src/main/java/org/finos/springbot/teams/bot/ChannelServiceController.java
> +import com.microsoft.bot.builder.ChannelServiceHandler;
... and this one

2023-07-12 08:34 UTC, robmoffat commented
Fixing #405

2023-07-14 09:12 UTC, vaibhav-db commented
@robmoffat  please check, I have revert the logger changes and added java code for com.microsoft.bot:bot-integration-spring class.

2023-07-14 12:57 UTC, robmoffat approved these changes

2023-07-17 11:27 UTC, merged